### ISSUE TITLE
怎么使用

### ISSUE THREAD

**Issue by niancan** [Evan2698/lwip2socks#1]
如何编译？

**Comment by Evan2698** [comment]
这个编译android 和ios 吧。
你需要使用go get 将所有依赖拉下来，不能使用go mod,  然后用


gomobile bind -target=android -ldflags="-s -w" “[你的目录]/lwip2socks/mobile” 进行编译，其实这个基本上就是 https://github.com/eycorsican/go-tun2socks.git 这个人的代码，我修改了一下，然后编译测试一下。后续不怎么维护。


我现在用的是 https://github.com/Evan2698/MyChimney.git ,这里面的AAR 是 https://github.com/Evan2698/chimney-go.git 工程中代码编译的。后续我只维护这个，基本上就是自己用。


因为 gomobile 是不支持go mod 的，所以你依然还要用go get 获取所有依赖，然后使用
gomobile bind -target=android -ldflags="-s -w" /home/evan/GoWorks/src/chimney-go/tun4socks 就可以编译出来。 假设你是程序员。所以我就回复简单。






good luck!




Any questions pls let me know.

























在 2020-08-15 00:26:30，"siyan" <notifications@github.com> 写道：

如何编译？

**Comment by niancan** [comment]
thx u reply.
我正在寻找ios的tun2socks,我找到一个go-tun2socks-mobile 我可以编译出来framewrok 但是我无法使用,因为没有技术文档。
所以 如果 你可以提供方向  不剩感谢

**Comment by Evan2698** [comment]
go-tun2socks-mobile 

func StartSocks(packetFlow PacketFlow, proxyHost string, proxyPort int) {
	if packetFlow != nil {
		lwipStack = core.NewLWIPStack()
		core.RegisterTCPConnHandler(socks.NewTCPHandler(proxyHost, uint16(proxyPort)))
		core.RegisterUDPConnHandler(socks.NewUDPHandler(proxyHost, uint16(proxyPort), 2*time.Minute))
		core.RegisterOutputFn(func(data []byte) (int, error) {
			packetFlow.WritePacket(data)
			return len(data), nil
		})
	}
}

这个参数就是代理地址，需要你自己有一个代理的客户端，这个就是调用入口。


一般流程：
本地浏览器--> tun 设备--> **协议脱栈（将数据报还原成TCP或者UDP数据）**--> 本地代理（socks5, http etc)--->特定socket 到--》远程---》回应数据--》经过特定socket--> 本地代理--》**写入tun 设备**。 

一般脱栈，自己写或者使用lwip,  我自己写过一版，效果不如lwip, 所以就用lwip, go-tun2socks-mobile 就是完成加粗部分。剩下的部分，你要自己找其他代码。

**Comment by niancan** [comment]
thx u again for your reply
我将尝试你提供的技术方案,我想我在你的代码片段中找到了答案.
这是一次很好的技术交流。
非常感谢
